### ISSUE TITLE
Location icon comes back after restarting shell

### ISSUE THREAD

**Issue by anupam207** [alexanderad/gnome-shell-location-icon-autohide#1]
Steps:
1. Turn on the extension on the [extension page](https://extensions.gnome.org/extension/1274/location-icon-autohide/)
2. Observe the location icon vanishes
3. Restart GNOME shell by alt+f2+R+return
4. Observe the location icon comes back

Distro: Ubuntu GNOME 17.04, shell version 3.24.2

**Comment by alexanderad** [comment]
Thanks for the report. I added a PR to fix this, going to test this for other edge cases (like init upon login), and update the extension in the Shell Store soon.

**Comment by alexanderad** [comment]
Version 2 has been just approved, please re-install your copy. Thank you for the report, @anupam207!
